name: root
channels:
- anaconda
- r
- bioconda
- conda-forge
- defaults
dependencies:
- bkcharts=0.2=py35_0
- bokeh=0.12.6=py35_0
- cycler=0.10.0=py35_0
- ipywidgets=6.0.0=py35_0
- jupyter=1.0.0=py35_3
- jupyter_console=5.2.0=py35_0
- matplotlib=2.0.2=np113py35_0
- mkl=2017.0.3=0
- nltk=3.2.4=py35_0
- pandas=0.20.3=py35_0
- pyqt=5.6.0=py35_2
- pytz=2017.2=py35_0
- pyyaml=3.12=py35_0
- qtconsole=4.3.1=py35_0
- sip=4.18=py35_0
- widgetsnbextension=3.0.1=py35_0
- jemalloc=4.5.0=0
- ruby=2.2.3=0
- tbb=4.4_20150728=0
- arpack=3.5.0=blas_openblas_201
- blas=1.1=openblas
- conda=4.3.27=py35_0
- conda-env=2.6.0=0
- fftw=3.3.6=3
- gsl=2.2.1=blas_openblas_2
- julia=0.6.0=blas_openblas_200
- libgit2=0.25.1=0
- metis=5.1.0=3
- mpfr=3.1.5=0
- numpy=1.13.3=py35_blas_openblas_200
- openblas=0.2.19=2
- openlibm=0.5.4=0
- openspecfun=0.5.3=0
- pcre2=10.21=3
- ply=3.10=py35_0
- setproctitle=1.1.10=py35_0
- suitesparse=4.5.4=blas_openblas_200
- xonsh=0.5.12=py35_2
- asn1crypto=0.22.0=py35_0
- bleach=1.5.0=py35_0
- bzip2=1.0.6=3
- cairo=1.14.8=0
- cffi=1.10.0=py35_0
- cryptography=1.8.1=py35_0
- curl=7.54.1=0
- dbus=1.10.20=0
- decorator=4.1.2=py35_0
- entrypoints=0.2.3=py35_0
- expat=2.1.0=0
- font-ttf-dejavu-sans-mono=2.37=0
- font-ttf-inconsolata=2.000=0
- font-ttf-source-code-pro=2.030=0
- font-ttf-ubuntu=0.83=0
- fontconfig=2.12.1=3
- fonts-continuum=1=0
- freetype=2.5.5=2
- glib=2.50.2=1
- gmp=6.1.0=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- harfbuzz=0.9.39=2
- html5lib=0.9999999=py35_0
- icu=54.1=0
- idna=2.6=py35_0
- ipykernel=4.6.1=py35_0
- ipython=6.1.0=py35_0
- ipython_genutils=0.2.0=py35_0
- jbig=2.1=0
- jedi=0.10.2=py35_2
- jinja2=2.9.6=py35_0
- jpeg=9b=0
- jsonschema=2.6.0=py35_0
- jupyter_client=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- krb5=1.13.2=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libssh2=1.8.0=0
- libtiff=4.0.6=3
- libuuid=1.0.3=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- markupsafe=1.0=py35_0
- mistune=0.7.4=py35_0
- nbconvert=5.2.1=py35_0
- nbformat=4.4.0=py35_0
- ncurses=5.9=10
- notebook=5.0.0=py35_0
- openssl=1.0.2l=0
- packaging=16.8=py35_0
- pandoc=1.15.0.6=0
- pandocfilters=1.4.1=py35_0
- pango=1.40.3=1
- path.py=10.3.1=py35_0
- pcre=8.39=1
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.15=py35_0
- ptyprocess=0.5.2=py35_0
- pycosat=0.6.2=py35_0
- pycparser=2.18=py35_0
- pygments=2.2.0=py35_0
- pyopenssl=17.0.0=py35_0
- pyparsing=2.2.0=py35_0
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.2=5
- readline=6.2=2
- requests=2.14.2=py35_0
- ruamel_yaml=0.11.14=py35_1
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.18=0
- tornado=4.5.1=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- r-assertthat=0.2.0=r3.4.1_0
- r-backports=1.1.0=r3.4.1_0
- r-base=3.4.1=0
- r-base64enc=0.1_3=r3.4.1_0
- r-bh=1.62.0_1=r3.4.1_0
- r-bindr=0.1=r3.4.1_0
- r-bindrcpp=0.2=r3.4.1_0
- r-bitops=1.0_6=r3.4.1_2
- r-boot=1.3_19=r3.4.1_0
- r-broom=0.4.2=r3.4.1_0
- r-car=2.1_4=r3.4.1_0
- r-caret=6.0_76=r3.4.1_0
- r-catools=1.17.1=r3.4.1_2
- r-cellranger=1.1.0=r3.4.1_0
- r-class=7.3_14=r3.4.1_0
- r-cluster=2.0.6=r3.4.1_0
- r-codetools=0.2_15=r3.4.1_0
- r-colorspace=1.3_2=r3.4.1_0
- r-crayon=1.3.2=r3.4.1_0
- r-curl=2.6=r3.4.1_0
- r-data.table=1.10.4=r3.4.1_0
- r-dbi=0.6_1=r3.4.1_0
- r-dichromat=2.0_0=r3.4.1_2
- r-digest=0.6.12=r3.4.1_0
- r-dplyr=0.7.0=r3.4.1_0
- r-essentials=1.6.0=r3.4.1_0
- r-evaluate=0.10=r3.4.1_0
- r-forcats=0.2.0=r3.4.1_0
- r-foreach=1.4.3=r3.4.1_0
- r-foreign=0.8_68=r3.4.1_0
- r-formatr=1.5=r3.4.1_0
- r-ggplot2=2.2.1=r3.4.1_0
- r-gistr=0.4.0=r3.4.1_0
- r-glmnet=2.0_10=r3.4.1_0
- r-glue=1.1.1=r3.4.1_0
- r-gtable=0.2.0=r3.4.1_0
- r-haven=1.0.0=r3.4.1_0
- r-hexbin=1.27.1=r3.4.1_0
- r-highr=0.6=r3.4.1_0
- r-hms=0.3=r3.4.1_0
- r-htmltools=0.3.6=r3.4.1_0
- r-htmlwidgets=0.8=r3.4.1_1
- r-httpuv=1.3.3=r3.4.1_0
- r-httr=1.2.1=r3.4.1_0
- r-irdisplay=0.4.4=r3.4.1_0
- r-irkernel=0.7.1=r3.4.1_0
- r-iterators=1.0.8=r3.4.1_0
- r-jsonlite=1.5=r3.4.1_0
- r-kernsmooth=2.23_15=r3.4.1_0
- r-knitr=1.16=r3.4.1_0
- r-labeling=0.3=r3.4.1_2
- r-lattice=0.20_35=r3.4.1_0
- r-lazyeval=0.2.0=r3.4.1_0
- r-lme4=1.1_13=r3.4.1_0
- r-lubridate=1.6.0=r3.4.1_0
- r-magrittr=1.5=r3.4.1_2
- r-maps=3.2.0=r3.4.1_0
- r-markdown=0.8=r3.4.1_0
- r-mass=7.3_47=r3.4.1_0
- r-matrix=1.2_10=r3.4.1_0
- r-matrixmodels=0.4_1=r3.4.1_0
- r-mgcv=1.8_17=r3.4.1_0
- r-mime=0.5=r3.4.1_0
- r-minqa=1.2.4=r3.4.1_2
- r-mnormt=1.5_5=r3.4.1_0
- r-modelmetrics=1.1.0=r3.4.1_0
- r-modelr=0.1.0=r3.4.1_0
- r-munsell=0.4.3=r3.4.1_0
- r-nlme=3.1_131=r3.4.1_0
- r-nloptr=1.0.4=r3.4.1_2
- r-nnet=7.3_12=r3.4.1_0
- r-openssl=0.9.6=r3.4.1_0
- r-packrat=0.4.8_1=r3.4.1_0
- r-pbdzmq=0.2_6=r3.4.1_0
- r-pbkrtest=0.4_7=r3.4.1_0
- r-pkgconfig=2.0.1=r3.4.1_0
- r-pki=0.1_3=r3.4.1_0
- r-plogr=0.1_1=r3.4.1_0
- r-plyr=1.8.4=r3.4.1_0
- r-pryr=0.1.2=r3.4.1_0
- r-psych=1.7.5=r3.4.1_0
- r-purrr=0.2.2.2=r3.4.1_0
- r-quantmod=0.4_9=r3.4.1_0
- r-quantreg=5.33=r3.4.1_0
- r-r6=2.2.1=r3.4.1_0
- r-randomforest=4.6_12=r3.4.1_0
- r-rbokeh=0.5.0=r3.4.1_0
- r-rcolorbrewer=1.1_2=r3.4.1_3
- r-rcpp=0.12.11=r3.4.1_0
- r-rcppeigen=0.3.3.3.0=r3.4.1_0
- r-rcurl=1.95_4.8=r3.4.1_0
- r-readr=1.1.1=r3.4.1_0
- r-readxl=1.0.0=r3.4.1_0
- r-recommended=3.4.1=r3.4.1_0
- r-rematch=1.0.1=r3.4.1_0
- r-repr=0.10=r3.4.1_0
- r-reshape2=1.4.2=r3.4.1_0
- r-rjsonio=1.3_0=r3.4.1_2
- r-rlang=0.1.1=r3.4.1_0
- r-rmarkdown=1.5=r3.4.1_0
- r-rpart=4.1_11=r3.4.1_0
- r-rprojroot=1.2=r3.4.1_0
- r-rsconnect=0.8=r3.4.1_0
- r-rstudioapi=0.6=r3.4.1_0
- r-rvest=0.3.2=r3.4.1_0
- r-scales=0.4.1=r3.4.1_0
- r-selectr=0.3_1=r3.4.1_0
- r-shiny=1.0.3=r3.4.1_0
- r-sourcetools=0.1.6=r3.4.1_0
- r-sparsem=1.77=r3.4.1_0
- r-spatial=7.3_11=r3.4.1_0
- r-stringi=1.1.5=r3.4.1_0
- r-stringr=1.2.0=r3.4.1_0
- r-survival=2.41_3=r3.4.1_0
- r-tibble=1.3.3=r3.4.1_0
- r-tidyr=0.6.3=r3.4.1_0
- r-tidyverse=1.1.1=r3.4.1_0
- r-ttr=0.23_1=r3.4.1_0
- r-uuid=0.1_2=r3.4.1_0
- r-xml2=1.1.1=r3.4.1_0
- r-xtable=1.8_2=r3.4.1_0
- r-xts=0.9_7=r3.4.1_2
- r-yaml=2.1.14=r3.4.1_0
- r-zoo=1.8_0=r3.4.1_0
- rstudio=1.0.153=1
- pip:
  - agate==1.6.0
  - agate-dbf==0.2.0
  - agate-excel==0.2.1
  - agate-sql==0.5.2
  - appdirs==1.4.3
  - args==0.1.0
  - arrow==0.10.0
  - astor==0.5
  - astroid==1.5.3
  - autopep8==1.3.2
  - babel==2.5.1
  - beautifulsoup4==4.6.0
  - binaryornot==0.4.4
  - chardet==3.0.4
  - click==6.7
  - clint==0.5.1
  - cookiecutter==1.5.1
  - csvkit==1.0.2
  - dbfread==2.0.7
  - docker-py==1.10.6
  - docker-pycreds==0.2.1
  - docopt==0.6.2
  - dulwich==0.18.4
  - edn-format==0.5.13
  - et-xmlfile==1.0.1
  - exofrills==0.1.14
  - future==0.16.0
  - hy==0.13.0+138.gdb21092
  - ipython-genutils==0.2.0
  - isodate==0.5.4
  - isort==4.2.15
  - jdcal==1.3
  - jinja2-time==0.2.0
  - jrnl==1.9.8
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - keyring==10.4.0
  - lazy-object-proxy==1.3.1
  - lazyasd==0.1.3
  - leather==0.3.3
  - lxml==3.8.0
  - mccabe==0.6.1
  - oauthlib==2.0.2
  - odfpy==1.3.5
  - openpyxl==2.4.8
  - osquery==2.2.1
  - parsedatetime==2.4
  - pipreqs==0.4.9
  - poyo==0.4.1
  - prompt-toolkit==1.0.15
  - ptpython==0.41
  - pycodestyle==2.3.1
  - pylint==1.7.2
  - pyrfc3339==1.0
  - python-slugify==1.2.4
  - pytimeparse==1.1.7
  - records==0.5.2
  - requests-oauthlib==0.8.0
  - rply==0.7.5
  - secretstorage==2.3.1
  - sh==1.12.14
  - sqlalchemy==1.1.14
  - tablib==0.12.1
  - thrift==0.10.0
  - toml==0.9.3
  - tweepy==3.5.0
  - tzlocal==1.4
  - unicodecsv==0.14.1
  - unidecode==0.4.21
  - urwid==1.3.1
  - websocket-client==0.44.0
  - whichcraft==0.4.1
  - wrapt==1.10.11
  - xlrd==1.1.0
  - xlwt==1.3.0
  - xmltodict==0.11.0
  - xonda==0.1.7
  - xonsh-apt-tabcomplete==0.1.4
  - xonsh-autoxsh==0.2
  - xonsh-click-tabcomplete==0.5
  - xonsh-docker-tabcomplete==0.1.4
  - xonsh-scrapy-tabcomplete==0.25
  - xonsh-vox-tabcomplete==0.4
  - xontrib-avox==0.6
  - xontrib-fzf-widgets==0.0.2
  - xontrib-powerline==0.4.0
  - xontrib-prompt-vi-mode==0.1.2
  - xontrib-z==0.3
  - yarg==0.1.9
prefix: /home/eklavya/miniconda3

